perform a find

diff --git a/PKG_Recipes/JMP.pkg.recipe.yaml b/PKG_Recipes/JMP.pkg.recipe.yaml
--- a/PKG_Recipes/JMP.pkg.recipe.yaml
+++ b/PKG_Recipes/JMP.pkg.recipe.yaml
@@ -69,6 +69,13 @@ Process:
         DIR=$(dirname "$0")
         MAJOR="%MAJOR_VERSION%"
 
+        # eject any existing mounted JMP volumes
+        for path in /Volumes/JMP*; do
+            [ -d "${path}" ] || continue # if not a directory, skip
+            dirname="$(basename "${path}")"
+            hdiutil eject ${path}
+        done
+
         # attach main image
         echo "Mounting JMP image"
         if ! hdiutil attach ${DIR}/JMP_${MAJOR}.dmg -nobrowse -mountpoint /Volumes/JMP_image; then
@@ -78,10 +85,9 @@ Process:
 
         # attach installer image, located inside main image
         echo "Mounting JMP installer image"
-        if [[ -f "/Volumes/JMP_image/JMP/JMP/${MAJOR}/Macintosh/JMP-Install.dmg" ]]; then
-          if ! hdiutil attach /Volumes/JMP_image/JMP/JMP/${MAJOR}/Macintosh/JMP-Install.dmg -nobrowse -mountpoint /Volumes/JMP_installer_image; then
-            echo "Failed to mount JMP-Install.dmg"
-          fi
+        if ! find /Volumes/JMP_image/JMP/JMP -name "*.dmg" -exec hdiutil attach {} -nobrowse -mountpoint /Volumes/JMP_installer_image \; ; then
+          echo "Failed to mount JMP-Install.dmg"
+        fi
         else
           echo "JMP installer image not found at /Volumes/JMP_image/JMP/JMP/${MAJOR}/Macintosh/JMP-Install.dmg"
           exit 1
